SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=1;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=1;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `HR_SYSTEM` DEFAULT CHARACTER SET utf8 ;
USE `HR_SYSTEM` ;

CREATE TABLE IF NOT EXISTS users (
id BIGINT NOT NULL AUTO_INCREMENT,
user_role VARCHAR (20) NOT NULL,
first_name VARCHAR (30) NOT NULL,
last_name VARCHAR (30) NOT NULL,
PRIMARY KEY (id)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1000;

CREATE TABLE IF NOT EXISTS users_log (
user_id BIGINT NOT NULL,
email VARCHAR (50) NOT NULL,
password VARCHAR (40) NOT NULL
)
ENGINE = InnoDB;

ALTER TABLE users_log
ADD FOREIGN KEY (user_id) REFERENCES users (id);

CREATE TABLE IF NOT EXISTS employees (
id BIGINT NOT NULL AUTO_INCREMENT,
first_name VARCHAR (20) NOT NULL,
last_name VARCHAR (20) NOT NULL,
age TINYINT,
PRIMARY KEY (id)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1000;

CREATE TABLE IF NOT EXISTS user_employees (
id BIGINT NOT NULL AUTO_INCREMENT,
user_id BIGINT NOT NULL,
employee_id BIGINT NOT NULL,
employee_add_date DATETIME NOT NULL,
employee_out_date DATETIME,
PRIMARY KEY (id)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1000;

ALTER TABLE user_employees
ADD FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_employees
ADD FOREIGN KEY (employee_id) REFERENCES employees (id);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;