SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=1;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=1;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS real_estate
DEFAULT CHARACTER SET utf8 ;
USE real_estate;

CREATE TABLE IF NOT EXISTS `offer` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(200) NOT NULL,
  `category` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `price` DOUBLE NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = InnoDB
AUTO_INCREMENT = 0;


CREATE TABLE IF NOT EXISTS `registered_user` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(200) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `email` VARCHAR(100),
  PRIMARY KEY (id)
)
ENGINE = InnoDB
AUTO_INCREMENT = 0;


CREATE TABLE IF NOT EXISTS `user_offers` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `registered_user_id` INTEGER NOT NULL,
  `offer_id` INTEGER NOT NULL,
  `offer_create_date` DATETIME NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (`registered_user_id`) REFERENCES `registered_user`(`id`),
  FOREIGN KEY (`offer_id`) REFERENCES `offer`(`id`)
)
ENGINE = InnoDB
AUTO_INCREMENT = 0;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;